version: "3.8"

# This file overrides Namo services for development integration
services:
  # Override Namo database for development
  db:
    container_name: namo-db-dev
    networks:
      - grabler-network
    ports:
      - "5432:5432" # Keep port for development access

  # Override Namo backend for development
  backend:
    container_name: namo-backend-dev
    networks:
      - grabler-network
    ports:
      - "8000:8000" # Keep port for development access
    environment:
      DATABASE_HOST: namo-db-dev
      CORS_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://namo.localhost:8080"

  # Override Namo frontend for development
  frontend:
    container_name: namo-frontend-dev
    networks:
      - grabler-network
    ports:
      - "5173:5173" # Keep port for development access
    environment:
      VITE_API_URL: "http://localhost:8000"

networks:
  grabler-network:
    external: true
