# Traefik static configuration
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  # Remove websecure since DSM handles SSL termination

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
# Remove certificatesResolvers since DSM handles SSL certificates
# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: felix.grabler02@gmail.com
#       storage: /acme/acme.json
#       dnsChallenge:
#         provider: cloudflare
#         delayBeforeCheck: 60s
#         resolvers:
#           - "1.1.1.1:53"
#           - "8.8.8.8:53"
# Fallback to HTTP challenge if needed
# httpChallenge:
#   entryPoint: web
# Optional: Enable access logs
# accessLog: {}

# Optional: Enable metrics
# metrics:
#   prometheus: {}
