# Traefik static configuration
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: felix.grabler02@gmail.com
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web
# Optional: Enable access logs
# accessLog: {}

# Optional: Enable metrics
# metrics:
#   prometheus: {}
